[greeter]
# gENiuS LightDM Login Theme

# Background — gENiuS wallpaper
background = /usr/share/backgrounds/gENiuS/gENiuS_wallpaper.jpeg

# Theme
theme-name = gENiuS-Dark
icon-theme-name = Papirus-Dark
font-name = JetBrains Mono 11
cursor-theme-name = Adwaita
cursor-theme-size = 24

# Panel
indicators = ~host;~spacer;~clock;~spacer;~power
clock-format = %A, %d %b  %H:%M
position = 50%,center 50%,center

# User list
hide-user-image = false
user-image = /usr/share/backgrounds/gENiuS/genius_ico.png
default-user-image = /usr/share/backgrounds/gENiuS/genius_ico.png

# Accessibility
reader =
at-spi-enabled = false
a11y-states = -contrast;-font;-keyboard;-reader

# Appearance
screensaver-timeout = 60
